# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-03 10:44
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuxProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.BigIntegerField()),
                ('profile_photo', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('is_guide', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_rating', models.BigIntegerField(default=5)),
                ('number_of_rating', models.BigIntegerField(default=1)),
                ('id_card', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('address', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('dux_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookmyguide.DuxProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('average_time', models.BigIntegerField(default=30)),
                ('price', models.BigIntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='places',
            field=models.ManyToManyField(to='bookmyguide.Places'),
        ),
    ]
