# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-03 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyguide', '0003_auto_20180203_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='photo',
            field=models.TextField(blank=True),
        ),
    ]
